version: '3.7'
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: journey_password
      POSTGRES_DB: journey
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local