export const cities : string[] = [
  "São Paulo, São Paulo, Brasil",
  "Rio de Janeiro, Rio de Janeiro, Brasil",
  "Belo Horizonte, Minas Gerais, Brasil",
  "Brasília, Distrito Federal, Brasil",
  "Curitiba, Paraná, Brasil",
  "Salvador, Bahia, Brasil",
  "Fortaleza, Ceará, Brasil",
  "Porto Alegre, Rio Grande do Sul, Brasil",
  "Recife, Pernambuco, Brasil",
  "Manaus, Amazonas, Brasil",
  "Florianópolis, Santa Catarina, Brasil",
  "Natal, Rio Grande do Norte, Brasil",
  "João Pessoa, Paraíba, Brasil",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Montevidéu, Uruguai",
  "Lima, Peru",
]